fallback-grpc-addr: 127.0.0.1:3030

consul: 
  addr: 127.0.0.1:8500

order:
  service-name: order
  server-to-run: http
  http-addr: 127.0.0.1:8080
  grpc-addr: 127.0.0.1:5050

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 127.0.0.1:8081
  grpc-addr: 127.0.0.1:5051

payment:
  service-name: payment
  server-to-run: http
  http-addr: 127.0.0.1:8082
  grpc-addr: 127.0.0.1:5052

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672
  
stripe-key: "${STRIPE_KEY}"
stripe-endpoint-secret: "${STRIPE_ENDPOINT_SECRET}"

grpc-dial-timeout: 20

jaeger:
  url: "http://127.0.0.1:14268/api/traces"